# Generated by Django 4.1.3 on 2023-01-11 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Appss', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userotp',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
    ]
