# Generated by Django 4.1.3 on 2023-01-11 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Appss', '0002_userotp_is_verified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userotp',
            name='is_verified',
            field=models.IntegerField(default=False),
        ),
    ]
