# Generated by Django 4.1.4 on 2023-01-12 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Appss', '0003_alter_userotp_is_verified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userotp',
            name='otp',
            field=models.IntegerField(),
        ),
    ]
